# Generated by Django 3.0.3 on 2025-02-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
