# Generated by Django 3.0.3 on 2025-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
