# Generated by Django 3.0.3 on 2025-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20251003_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-end_date'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
