# Generated by Django 5.2.7 on 2025-10-08 21:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_about_id_alter_contactinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
